defaults: &defaults
  CARRIERWAVE_STORAGE: :fog
  GOOGLE_ANALYTICS_ID: 
  AIRBRAKE_API_KEY: 
  AIRBRAKE_HOST: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_REGION: 
  AWS_BUCKET: 
  HOME_CAST_ID: 
  COLOR_CHECK_CAST_ID: 

development:
  <<: *defaults
  EMAIL_HOST: "localhost:3000"
  CARRIERWAVE_STORAGE: :file
  TWITTER_CONSUMER_KEY: "qAFaJs7lyIm3xjtdtFaQ"
  TWITTER_CONSUMER_SECRET: "Ytqj4IfXmQ7gn0yWf2GgFUpFDAWfqYpVkX3P1ng0TU"
  GITHUB_CONSUMER_KEY: "455d7cde838004d7d46a"
  GITHUB_CONSUMER_SECRET: "5e076dbe06e79f6a7e329a4c7b306c0a0c6055c1"
  COLOR_CHECK_CAST_ID: 1

bugfix:
  <<: *defaults
  CARRIERWAVE_STORAGE: :fog

production:
  <<: *defaults
  EMAIL_HOST: "ascii.io"
  CARRIERWAVE_STORAGE: :fog

test:
  <<: *defaults
  EMAIL_HOST: "example.org"
  CARRIERWAVE_STORAGE: :file
